# Generated by Django 4.2.3 on 2023-08-11 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Characters_All_Channels_Objects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "characters_unique",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticker_Extraction_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "channel_image",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "ticker_image",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=15, null=True)),
                ("time", models.CharField(blank=True, max_length=12, null=True)),
                ("text_ocr", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="words_to_be_searched_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
