# Generated by Django 4.2.1 on 2023-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_comparing', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker_Extraction_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_image', models.CharField(blank=True, max_length=60, null=True)),
                ('ticker_image', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=15, null=True)),
                ('time', models.CharField(blank=True, max_length=12, null=True)),
                ('text_ocr', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
