# Generated by Django 4.2.1 on 2023-06-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker_extraction_model',
            name='channel_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
