# Generated by Django 4.2.1 on 2023-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ticker_extraction_model_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_comparison',
            name='characters_comparing',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ticker_extraction_model',
            name='channel_image',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
